add optional toggle to load remote profile images
damus-io/damus pull request #127
Opened 2022-12-23 19:23 UTC by radixrat

Potential solution for https://github.com/damus-io/damus/issues/124 once toggled all images come from robohash instead of  loading from remote profiles

2022-12-23 19:30 UTC, radixrat commented
Looks like this only restricts for main timeline need to restrict in full profile view as well, may look later

2022-12-23 20:22 UTC, radixrat commented
<img width="349" alt="option-off" src="https://user-images.githubusercontent.com/58019185/209402420-ae26ca3f-7f85-453c-bc7f-bc3f6fbf5945.png">
<img width="349" alt="option-off-view" src="https://user-images.githubusercontent.com/58019185/209402429-707fe9bc-e7e4-4b9a-b1b8-7e4d5ffa70f9.png">


<img width="337" alt="option-on" src="https://user-images.githubusercontent.com/58019185/209402394-25eeff53-fab9-47ce-ab5d-3b4e9fd75dfd.png">
<img width="340" alt="option-on-view" src="https://user-images.githubusercontent.com/58019185/209402400-a9d61e54-4d2b-422f-b10d-71d036219778.png">
<img width="343" alt="option-on-full-profile" src="https://user-images.githubusercontent.com/58019185/209402406-707ad80a-8437-4774-8caa-5ab3d74fabae.png">

2022-12-23 20:24 UTC, radixrat commented
when swapping the setting any profiles that were immediately loaded on home view before toggling will still show with previous setting until you scroll down to get more profiles, but I believe this should be blocking anymore remote requests aside from robohash

2022-12-23 20:46 UTC, 0xtlt commented
Maybe we can have a picker with 3 or 4 options:

- Load all images (insecure) -> will load http and https images
- Load secured images -> will only load https images
- Load contact images -> will only load people in our contact list
- No external images -> will only load robot hash

We can simplify it with 3 options I think

2022-12-23 20:56 UTC, radixrat commented
> Maybe we can have a picker with 3 or 4 options:
> 
> * Load all images (insecure) -> will load http and https images
> * Load secured images -> will only load https images
> * Load contact images -> will only load people in our contact list
> * No external images -> will only load robot hash
> 
> We can simplify it with 3 options I think

yeh I think your load all images, load contacts only, and load no external would be good. http/https won’t matter as much if they are worried about ip logging. I’ll have to see if we have a way of determining relation of profile when this image url is set. Thanks.

2022-12-24 03:19 UTC, radixrat commented
Added three levels of choice:

- Everyone (default)
- Friends Only
- Restricted 

<img width="324" alt="Screenshot 2022-12-23 at 10 15 11 PM" src="https://user-images.githubusercontent.com/58019185/209419346-d774a52d-9c96-491b-8033-7327e760507a.png">


<img width="332" alt="Screenshot 2022-12-23 at 10 15 18 PM" src="https://user-images.githubusercontent.com/58019185/209419349-219ca051-427b-4e03-be45-139eb3e3d3b9.png">

Not following jb55:

<img width="350" alt="Screenshot 2022-12-23 at 10 15 49 PM" src="https://user-images.githubusercontent.com/58019185/209419352-f6b20d68-e0d8-429f-a227-eb19264be6e7.png">

After following:

<img width="313" alt="Screenshot 2022-12-23 at 10 16 14 PM" src="https://user-images.githubusercontent.com/58019185/209419369-ac13a841-5c11-4825-b12b-1bf5fcbceb49.png">

Everyone else in feed I am not following from this dummy account:
<img width="357" alt="Screenshot 2022-12-23 at 10 16 37 PM" src="https://user-images.githubusercontent.com/58019185/209419376-d2954df1-bd3d-42cc-ac31-d816b58dcb32.png">

2022-12-24 03:57 UTC, radixrat commented
@jb55 let me know if this is something we might be interested in for future or if you have any alternate suggestions, I just heard some people talking about it in forums so thought I would take a shot at it.

2022-12-24 10:06 UTC, 0xtlt commented
Working for me but "Restricted" should be more expressive for non tech people

2022-12-24 10:10 UTC, 0xtlt requested changes

2022-12-24 10:10 UTC, 0xtlt commented on damus/Views/ConfigView.swift
> +    @AppStorage("remote_image_policy") var remote_image_policy: String = "everyone"
Don't know if it's possible but can we use enum for the value ?

2022-12-24 12:31 UTC, 0xtlt commented
Hey!
I just made a PR to your PR branch: https://github.com/radixrat/damus/pull/1

It contains the working version with enum update :)

2022-12-24 12:59 UTC, radixrat commented
> Hey! I just made a PR to your PR branch: [radixrat#1](https://github.com/radixrat/damus/pull/1)
> 
> It contains the working version with enum update :)

nice, this is much cleaner, I merged it, thanks!  What is your opinion on a better word for "Restricted"? would "Block All" give a better indication to end user?

2022-12-24 14:35 UTC, 0xtlt commented
In the code you merged, I changed by "Restricted (no remote image)"

Maybe "Block images" can be better

2022-12-24 14:37 UTC, 0xtlt commented
Another thing : If we're going to block profile images, we might block post images/gif as well
So, all external contents

2022-12-24 14:41 UTC, radixrat commented
> Another thing : If we're going to block profile images, we might block post images/gif as well
> So, all external contents

Yeh believe this could be expanded to cover all image cases, I know there is a block of code that currently restricts image loading to only friends, I think this setting could be leveraged there.

One thing is I think we would want to have a friends of friends option in this case as well

2022-12-24 14:59 UTC, radixrat commented
Applied same policy to `should_show_images` we used for profile restrictions, so image loading should follow this setting now as well. One thing I think would be safer is to set the `default` to Friends of Friends instead of Everyone, the reason the code was initially put in place was to stop the porn bots so setting default to everyone would bring that issue back. 

when set to everyone can view images:
<img width="339" alt="Screenshot 2022-12-24 at 9 55 01 AM" src="https://user-images.githubusercontent.com/58019185/209441608-a2873809-9049-49b8-8518-0bf296cd3b83.png">

When restricted it will block:
<img width="336" alt="Screenshot 2022-12-24 at 9 55 23 AM" src="https://user-images.githubusercontent.com/58019185/209441617-9fe9d4a8-f454-4c77-9f37-d16395efc0bc.png">

2022-12-24 16:18 UTC, 0xtlt commented
Agreed with the default to friends only

I think we can activate friends of friends but if we add this option, I think we need to keep the friend only option too
And the option friends of friends can be time consuming to develop

Then maybe an improvement for a next time in another PR (or maybe someone can make it)

2022-12-24 16:22 UTC, radixrat commented
> Agreed with the default to friends only
> 
> I think we can activate friends of friends but if we add this option, I think we need to keep the friend only option too And the option friends of friends can be time consuming to develop
> 
> Then maybe an improvement for a next time in another PR (or maybe someone can make it)

Friends of friends is already implemented in contacts module, I added it alongside friends so options now are:

- Everyone
- Friends
- Friend of Friends
- Block Images 

think that should cover everything so far.

2022-12-24 16:26 UTC, 0xtlt commented
Can we swift friends and friends of friends in the list ?

2022-12-24 16:29 UTC, radixrat commented
> Can we invert friends and friends of friends in the list ?

done. makes mores sense with this ordering less restrictive -> more restrictive

2022-12-24 19:18 UTC, radixrat commented
```
let remote_image_policy: RemoteImagePolicy = RemoteImagePolicy(rawValue: UserDefaults.standard.string(forKey: "remote_image_policy")!) ?? .friendsOfFriends
```
this can cause crash if optional unwrapped is nil, looking at how to clear this

2022-12-26 11:25 UTC, 0xtlt approved these changes

2022-12-31 20:39 UTC, jb55 commented
sorry this got left behind... haven't had a change to review this one yet and looks like it needs rebased

2022-12-31 21:07 UTC, radixrat commented
rebased to current upstream

2023-01-09 11:05 UTC, BenGWeeks commented
I'm actually working on a Core ML porn detector that uses AI to return a value between 0 and 1 for images, where 1 would be extreme content. In the settings you could turn AI detection on.

2023-01-09 11:38 UTC, 0xtlt commented
Oh!

2023-01-09 14:09 UTC, radixrat commented
> Related - I'm actually working on a Core ML porn detector that uses AI to return a value between 0 and 1 for images, where 1 would be extreme content. In the settings you could turn AI detection on.

One issue is if it waits till it’s client side to detect, the image has already been retrieved so if you are at work or something it won’t save you from explaining why porn photos were downloaded 😂

2023-01-09 14:16 UTC, radixrat commented
Looks like out of date again I’ll try to rebase, think I need to factor in this new preview pane, if the goal is to not load the images at all from remote sources, I noticed it paints an outline before user clicks so think the image is getting loaded remotely anyways even if show images bool is false.

2023-01-09 14:20 UTC, paulrollo commented
Link would be downloaded but not the image itself until actually displayed
or prefetched by the client.

On Mon, 9 Jan 2023 at 14:09, radixrat ***@***.***> wrote:

> Related - I'm actually working on a Core ML porn detector that uses AI to
> return a value between 0 and 1 for images, where 1 would be extreme
> content. In the settings you could turn AI detection on.
>
> One issue is if it waits till it’s client side to detect, the image has
> already been retrieved so if you are at work or something it won’t save you
> from explaining why porn photos were downloaded 😂
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/damus-io/damus/pull/127#issuecomment-1375679207>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEWI45XPQEUG3HMJSUINE3WRQL3NANCNFSM6AAAAAATIAEIBY>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-01-09 14:48 UTC, radixrat commented
> Link would be downloaded but not the image itself until actually displayed or prefetched by the client.
> […](#)

so the porn ML detection is based on url name instead of actual content of the image?

2023-01-09 15:44 UTC, radixrat commented
> > > Link would be downloaded but not the image itself until actually displayed or prefetched by the client.
> > 
> > 
> > > […](#)
> > 
> > 
> > so the porn ML detection is based on url name instead of actual content of the image?
> 
> I haven't submitted the PR for that yet. I don't think it replaces these options, just an additional option (might put it under "experimental"). You pass the image into a method.

Yeh so this is a similar problem I am currently facing with the nice blurred preview pane, the image has to be client side before it can get a blurred version for the ImageCarousal, but by having the image client side to analyze it you've already loaded it from the remote source which means your work network sees you downloaded the porn content.

2023-01-10 19:01 UTC, jb55 commented
not sure what the state of this is, but ideally I would like to not load blurred images by default. right now they are downloaded and blurred which is not good

2023-01-10 19:59 UTC, radixrat commented
> not sure what the state of this is, but ideally I would like to not load blurred images by default. right now they are downloaded and blurred which is not good

I’ll see if I can remove the image preview and add back as links (in case user wants to click through) if their remote load images policy doesn’t align tonight, looks like PR is out of date again so I’ll rebase it

2023-01-11 01:43 UTC, radixrat commented
@jb55 @0xtlt okay updated code to only set image URLs into the `img_urls` list of the `render_note_content` if show_images is set to true (as well as the extension matching which was already there), this is based on the remote image policy a user has selected under settings: everyone, friend of friend, friends only, and block images.

Block Images example (pfp is robohash, image is a link):
<img width="350" alt="Screenshot 2023-01-10 at 8 30 55 PM" src="https://user-images.githubusercontent.com/58019185/211697509-41dca716-6d5f-4b51-9136-82ac728d7657.png">
<img width="349" alt="Screenshot 2023-01-10 at 8 30 25 PM" src="https://user-images.githubusercontent.com/58019185/211697534-4b658874-771c-4bb2-a293-3ce05abb5199.png">

Everyone image policy display example (pfp renders, images render):
<img width="328" alt="Screenshot 2023-01-10 at 8 31 03 PM" src="https://user-images.githubusercontent.com/58019185/211697567-f3b2717c-8995-4ae2-8a4c-af96a550a2d5.png">
<img width="343" alt="Screenshot 2023-01-10 at 8 31 18 PM" src="https://user-images.githubusercontent.com/58019185/211697588-21ccfd19-3275-4ce4-a8dd-280759a06e6b.png">
 

Default would be friend of friend, but this should let users set their setting to Block Images and not have to load any note or pfp images from anyone (if at work or something) and then set it back to friend of friend while at home.  People still should use VPN for now, but this might help a bit at least (some people want it for privacy as well (ip tracking) etc).

2023-01-11 07:55 UTC, 0xtlt commented
Seems good @radixrat 

I'm working btw on an open source projet to delegate the loading of remote contents like videos, gif, images and urls.

This is a first step and maybe my project, the second one to ensure the security of everyone using it :)

2023-02-02 22:09 UTC, radixrat commented
@jb55 PR for client configurable image loading is here and ive kept it up to date if you want to try it out.

2023-02-04 20:07 UTC, merged

2023-02-04 20:58 UTC, jb55 commented
thanks, I merged but made the default everyone like before