Polls
damus-io/damus pull request #243
Opened 2023-01-04 16:20 UTC by 0xtlt

Hello everyone,

I have developed a poll feature for Damus that uses Nostr's reaction kind 7 to allow for voting.

In Damus options, the user can choose to see the votes of their friends as well as their friends' friends, or from everyone. By default, it is set to friends + friends' friends to prevent bots from spamming opinions.

It is now possible to create polls directly from the post writing panel.

I have also included a fix in this PR that prevents Damus from associating any reaction to a like, which was previously the case even if it was a thumbs down for the example.

I hope you enjoy it, I have also included a screenshot here:

![Simulator Screen Shot - iPhone 14 Pro - 2023-01-04 at 17 13 30](https://user-images.githubusercontent.com/31560900/210600861-ab55e6a6-364e-4d7a-95b4-dbed57307fc3.png)

2023-01-04 19:40 UTC, BenGWeeks commented
Nice :-)

2023-01-05 18:45 UTC, jb55 commented
interesting...

2023-01-05 18:46 UTC, jb55 commented
why not just make it a different kind? it feels wrong using reactions for this.

2023-01-05 18:50 UTC, 0xtlt commented
I will try making a new NIP for that, just at the moment, I thought it wasn't necessary :)

2023-01-05 18:52 UTC, 0xtlt commented
Working on the NIP right now :)

2023-01-05 19:07 UTC, jb55 commented
but if you want to go for it lol

2023-01-05 19:13 UTC, 0xtlt commented
agreed, go and we gonna support both in the future if poll nip is accepted @jb55

2023-01-06 18:43 UTC, 0xtlt commented
I added the code of the NIP 41, when it will be accepted, I will change again the code if needed it will be ready to be merged :)

2023-01-06 18:44 UTC, 0xtlt commented
NIP 41 ref: https://github.com/nostr-protocol/nips/pull/148

2023-01-08 23:35 UTC, BenGWeeks commented
Would look cool with the linear gradient for the bars :-)

```
LinearGradient(gradient: Gradient(colors: [
    Color("DamusPurple"),
    Color("DamusBlue")
]), startPoint: .topTrailing, endPoint: .bottomTrailing)
```

2023-01-09 07:25 UTC, 0xtlt commented
> Would look cool with the linear gradient for the bars :-)
> 
> ```
> LinearGradient(gradient: Gradient(colors: [
>     Color("DamusPurple"),
>     Color("DamusBlue")
> ]), startPoint: .topTrailing, endPoint: .bottomTrailing)
> ```

Will add it today, thanks :)

2023-01-09 08:52 UTC, BenGWeeks commented
What does the Ui look like whilst creating the poll?

2023-01-09 09:21 UTC, 0xtlt commented
![simulator_screenshot_EF8E53E7-0C0D-4963-B9A2-656095C0DD71](https://user-images.githubusercontent.com/31560900/211275533-24bf3dbb-5e4e-48e5-97cb-95cbc90e9432.png)

@BenGWeeks

2023-01-09 09:39 UTC, BenGWeeks commented
With regards to the post button - was thinking better UX/UI would be to display but greyed out until created a message? (As apposed to hide, where I've thought to myself "if i write this message how will I be able to post it?")

2023-01-09 10:11 UTC, BenGWeeks commented
(That's generic to all posts)

2023-01-10 18:59 UTC, jb55 requested changes

2023-01-10 18:59 UTC, jb55 commented on damus/Views/EventView.swift
> +        if id == subscription_poll_uuid {
you can just use `guard id == subscription_poll_uuid` here

2023-01-10 18:59 UTC, jb55 commented on damus/Views/EventView.swift
> +                    VStack(alignment: .leading, spacing: 15) {
this should be its own view

2023-01-10 18:59 UTC, jb55 commented on damus/Views/ConfigView.swift
> +    @AppStorage("poll_results_everyone") var poll_results_everyone: Bool = false
I've never used AppStorage before. Does this just save it in UserSettings? I eventually want to scope user settings by pubkey so maybe its best to have it in there

2023-01-10 18:59 UTC, jb55 commented on damus/Models/HomeModel.swift
> +        }
Looks like this should be removed?

2023-01-10 18:59 UTC, jb55 commented on damus/Views/PostView.swift
> +                VStack(alignment: .leading, spacing: 15) {
this needs its own view

2023-07-31 19:12 UTC, jb55 commented
closing this for now since it's pretty out of date

2023-07-31 19:12 UTC, closed without merging