hashtag-suggestion-in-postview
damus-io/damus pull request #2604
Opened 2024-10-20 22:18 UTC by scoder1747

## Summary

This PR enables a user to see  Hash Tag Suggestion List in the Post View while composing a note. When user starts typing his word with '#', he will be able to see the list of trending hash-tags (or at least default hash-tags). This hash-tag data is collected from the Search-page and put into a static property SuggestedHashtagsView.lastRefresh_hashtags. This approach is light-weight as no-active network call is being triggered while the last refresh data is taken into account. After user taps one of the items in the list, the post will be appended with the clicked value (just as @ tagging approach being implemented currently).

Video demonstration:

https://github.com/user-attachments/assets/4829ce2b-13d8-435d-9361-eca1921d185a

_[Please provide a summary of the changes in this PR.]_

## Checklist

- [ ] I have read (or I am familiar with) the [Contribution Guidelines](../docs/CONTRIBUTING.md)
- [ ] I have tested the changes in this PR
- [ ] My PR is either small, or I have split it into smaller logical commits that are easier to review
- [ ] I have added the signoff line to all my commits. See [Signing off your work](../docs/CONTRIBUTING.md#sign-your-work---the-developers-certificate-of-origin)
- [ ] I have added appropriate changelog entries for the changes in this PR. See [Adding changelog entries](../docs/CONTRIBUTING.md#add-changelog-changed-changelog-fixed-etc)
    - [ ] I do not need to add a changelog entry. Reason: _[Please provide a reason]_
- [ ] I have added appropriate `Closes:` or `Fixes:` tags in the commit messages wherever applicable, or made sure those are not needed. See [Submitting patches](https://github.com/damus-io/damus/blob/master/docs/CONTRIBUTING.md#submitting-patches)

## Test report

_Please provide a test report for the changes in this PR. You can use the template below, but feel free to modify it as needed._

**Device:** _[Please specify the device you used for testing]_

**iOS:** _[Please specify the iOS version you used for testing]_

**Damus:** _[Please specify the Damus version or commit hash you used for testing]_

**Setup:** _[Please provide a brief description of the setup you used for testing, if applicable]_

**Steps:** _[Please provide a list of steps you took to test the changes in this PR]_

**Results:**
- [ ] PASS
- [ ] Partial PASS
  - Details: _[Please provide details of the partial pass]_

## Other notes

_[Please provide any other information that you think is relevant to this PR.]_

2024-10-21 15:24 UTC, alltheseas commented
@robagreda what do you think :eyes:

2024-10-26 18:44 UTC, jb55 requested changes

2024-10-26 18:44 UTC, jb55 commented on damus/Views/PostView.swift
> +    }
```suggestion
    guard let word,
          word.count >= 2,
          let first_char = word.first,
          first_char == "#" else {
        return nil
    }
```

2024-10-26 18:44 UTC, jb55 commented on damus/Views/SuggestedHashtagsView.swift
> +         isFromPostView: Bool = false,
this seems hacky, shouldn't this just be a different view entirely?

2024-10-28 00:20 UTC, scoder1747 commented on damus/Views/PostView.swift
> +    }
I have made the update

2024-10-28 19:49 UTC, closed without merging