Fix profile pic banner pic upload
damus-io/damus pull request #2614
Opened 2024-10-24 14:43 UTC by scoder1747

## Summary
The existing picture upload flow for Profile picture and Banner picture is broken. Root cause analysis of this bug is due to missing KeyPair parameter being passed while instantiating EditPictureControl objects. They KeyPair param is used to create nip98 signature and which is eventually used to create an "Authorization" header for creating an upload request.

_[Please provide a summary of the changes in this PR.]_

## Checklist

- [ ] I have read (or I am familiar with) the [Contribution Guidelines](../docs/CONTRIBUTING.md)
- [ ] I have tested the changes in this PR
- [ ] My PR is either small, or I have split it into smaller logical commits that are easier to review
- [ ] I have added the signoff line to all my commits. See [Signing off your work](../docs/CONTRIBUTING.md#sign-your-work---the-developers-certificate-of-origin)
- [ ] I have added appropriate changelog entries for the changes in this PR. See [Adding changelog entries](../docs/CONTRIBUTING.md#add-changelog-changed-changelog-fixed-etc)
    - [ ] I do not need to add a changelog entry. Reason: _[Please provide a reason]_
- [ ] I have added appropriate `Closes:` or `Fixes:` tags in the commit messages wherever applicable, or made sure those are not needed. See [Submitting patches](https://github.com/damus-io/damus/blob/master/docs/CONTRIBUTING.md#submitting-patches)

2024-10-24 15:00 UTC, jb55 commented
This looks right to me!

2024-10-24 15:02 UTC, jb55 commented
although nostr.build supports uploads without auth right? was it not working because the image was too large?

2024-10-24 15:02 UTC, jb55 approved these changes

2024-10-24 15:33 UTC, scoder1747 commented
> although nostr.build supports uploads without auth right? was it not working because the image was too large?

I thought it would support but as of now, the following is the response sent by nostr-build
Upload Error: Unauthorized, please provide a valid nip-98 token

There is one more commit that limits the profile and banner upload to image only and sets selection quantity to 1

2024-10-26 18:29 UTC, jb55 requested changes

2024-10-26 18:29 UTC, jb55 commented on damus/Views/MediaPicker.swift
> +        }
please use switch statement

2024-10-26 18:54 UTC, scoder1747 commented on damus/Views/MediaPicker.swift
> +        }
@jb55 I have made the update

2024-10-28 19:49 UTC, closed without merging