Add edit share and tap gesture in profile pic viewer
damus-io/damus pull request #2624
Opened 2024-10-27 13:26 UTC by scoder1747

## Summary
This PR adds Edit and Share buttons and includes tap gesture in the Profile Pic Image Viewer page. Edit button navigates to the current Edit profile page. The Share button here is unique in that it allows direct image file (not nost.build or any link) to be shared over Share Sheet (sharelink). Tap gesture hides/unhides buttons over tapping action on the page.

Tap gesture:
https://github.com/user-attachments/assets/855ef09a-bf92-4a0b-ac71-c9f1d90a313a

_[Please provide a summary of the changes in this PR.]_

## Checklist

- [ ] I have read (or I am familiar with) the [Contribution Guidelines](../docs/CONTRIBUTING.md)
- [ ] I have tested the changes in this PR
- [ ] My PR is either small, or I have split it into smaller logical commits that are easier to review
- [ ] I have added the signoff line to all my commits. See [Signing off your work](../docs/CONTRIBUTING.md#sign-your-work---the-developers-certificate-of-origin)
- [ ] I have added appropriate changelog entries for the changes in this PR. See [Adding changelog entries](../docs/CONTRIBUTING.md#add-changelog-changed-changelog-fixed-etc)
    - [ ] I do not need to add a changelog entry. Reason: _[Please provide a reason]_
- [ ] I have added appropriate `Closes:` or `Fixes:` tags in the commit messages wherever applicable, or made sure those are not needed. See [Submitting patches](https://github.com/damus-io/damus/blob/master/docs/CONTRIBUTING.md#submitting-patches)

## Test report

_Please provide a test report for the changes in this PR. You can use the template below, but feel free to modify it as needed._

**Device:** _[Please specify the device you used for testing]_

**iOS:** _[Please specify the iOS version you used for testing]_

**Damus:** _[Please specify the Damus version or commit hash you used for testing]_

**Setup:** _[Please provide a brief description of the setup you used for testing, if applicable]_

**Steps:** _[Please provide a list of steps you took to test the changes in this PR]_

**Results:**
- [ ] PASS
- [ ] Partial PASS
  - Details: _[Please provide details of the partial pass]_

## Other notes

_[Please provide any other information that you think is relevant to this PR.]_

2024-10-28 22:34 UTC, danieldaquino requested changes
Thank you @scoder1747 for your PR! While trying to review and test it, I have encountered a build error, which I believe is because the merge brought some changes that affect this code. Can you please check?

2024-10-28 22:34 UTC, danieldaquino commented on damus/Views/Images/ProfilePicImageView.swift
> +                        NavDismissBarView()
This line is failing to compile with the following error message: 

```
Missing argument for parameter 'navDismissBarContainer' in call
```

I believe it is due to a recent parallel change on `NavDismissBarView`, that now requires an argument for this call

2024-10-28 22:34 UTC, danieldaquino commented on damus/Views/Images/ProfilePicImageView.swift
> +                                      preview: SharePreview("Damus Profile", image: Image(uiImage: image))) {
We should localize "Damus Profile" by using `NSLocalizedString`

2024-10-29 00:41 UTC, scoder1747 commented
Thanks @danieldaquino! I’ve addressed your comments and made the updates.

2024-11-04 21:37 UTC, danieldaquino commented
Thank you @scoder1747! Changes look good and are working on my end as well!

**I squashed the commits into one and manually pushed to `master`: 6f044553501ff0141e8425ce8aa260f73e101913**

A few extra comments and tips in terms of git commits:
1. I noticed one changelog entry called "_Address PR feedback_". Don't worry about adding a changelog entry for each commit, they are only needed for user-facing changes
2. If you need to tweak your PR, sometimes it's ok to add more commits to your branch, but it can be helpful to learn how to use `git rebase --interactive` to edit past commits in your PR and keep a cleaner commit history.

Thank you!

2024-11-04 21:37 UTC, closed without merging