Added Alby Go to mobile wallets selection
damus-io/damus pull request #2668
Opened 2024-11-08 08:15 UTC by itstomekk

## Summary

Added Alby Go to mobile wallets selection

## Checklist

- [x ] I have read (or I am familiar with) the [Contribution Guidelines](../docs/CONTRIBUTING.md)
- [ ] I have tested the changes in this PR **- not sure about albygo::lightning handle, reviewing with alby team**
- [x ] My PR is either small, or I have split it into smaller logical commits that are easier to review
- [ ] I have added the signoff line to all my commits. See [Signing off your work](../docs/CONTRIBUTING.md#sign-your-work---the-developers-certificate-of-origin)
- [ ] I have added appropriate changelog entries for the changes in this PR. See [Adding changelog entries](../docs/CONTRIBUTING.md#add-changelog-changed-changelog-fixed-etc)
    - [x ] I do not need to add a changelog entry. Reason: _[very small change]_
- [x ] I have added appropriate `Closes:` or `Fixes:` tags in the commit messages wherever applicable, or made sure those are not needed. See [Submitting patches](https://github.com/damus-io/damus/blob/master/docs/CONTRIBUTING.md#submitting-patches)

## Other notes

_Simple patch, my first here, I'm not very experienced with github_

2024-11-08 17:39 UTC, jb55 approved these changes

2024-11-08 17:40 UTC, jb55 commented
looks good to me!

2024-11-15 21:04 UTC, danieldaquino commented
Thank you @itstomekk for the PR!

I gave it a try, but I noticed the logo is not showing up for some reason:

![Screenshot 2024-11-15 at 12 42 48](https://github.com/user-attachments/assets/e64cb3aa-d6e5-4afe-ac03-9f93f10be5a4)

I also noticed this error message:

```
No image named 'albygo' found in asset catalog for /Users/*****/Library/Developer/CoreSimulator/Devices/***********/data/Containers/Bundle/Application/************/damus.app
```

I believe there is a typo on the image name. When I apply this change locally the image appears:

```diff
diff --git a/damus/Models/Wallet.swift b/damus/Models/Wallet.swift
index 7693cb1c..5d82373c 100644
--- a/damus/Models/Wallet.swift
+++ b/damus/Models/Wallet.swift
@@ -93,7 +93,7 @@ enum Wallet: String, CaseIterable, Identifiable, StringCodable {
                          appStoreLink: "https://apps.apple.com/us/app/river-buy-mine-bitcoin/id1536176542", image: "river")
         case .albygo:
             return .init(index: 13, tag: "albygo", displayName: "Alby Go", link: "albygo:lightning:",
-                         appStoreLink: "https://apps.apple.com/us/app/alby-go/id6471335774", image: "albygo")
+                         appStoreLink: "https://apps.apple.com/us/app/alby-go/id6471335774", image: "alby-go")
             
         }
     }
```

Furthermore, I tried installing Alby Go on my phone and going through the link, but it always takes me to the App store page. Perhaps it would be best for us to wait for the Alby team's response on the `albygo:lightning:` handle before we merge this.

Can you please check these?

Thank you!

2024-11-15 23:43 UTC, danieldaquino requested changes
_(Marking this PR as "requested changes" to help me keep track of which PRs I need to look at. My review comments are in a previous comment)_

2024-11-16 17:11 UTC, jb55 commented
Thanks for testing it!

2025-01-05 14:06 UTC, itstomekk reviewed
fixed

2025-01-06 09:28 UTC, danieldaquino commented
Thank you @itstomekk! I confirm that the icon issue has been fixed!

However, I still had issues with opening the Alby Go link with Alby Go installed on my phone. I did a bit of digging and I found that this patch on to top of your PR seems to fix that:
```diff
diff --git a/damus/Info.plist b/damus/Info.plist
index e77d88a3..fb84175d 100644
--- a/damus/Info.plist
+++ b/damus/Info.plist
@@ -48,6 +48,7 @@
 	<key>LSApplicationQueriesSchemes</key>
 	<array>
 		<string>river</string>
+		<string>alby</string>
 		<string>albygo</string>
 		<string>bitcoinbeach</string>
 		<string>breez</string>
diff --git a/damus/Models/Wallet.swift b/damus/Models/Wallet.swift
index 83b33ff6..1c2552c4 100644
--- a/damus/Models/Wallet.swift
+++ b/damus/Models/Wallet.swift
@@ -92,7 +92,7 @@ enum Wallet: String, CaseIterable, Identifiable, StringCodable {
             return .init(index: 12, tag: "river", displayName: "River", link: "river://",
                          appStoreLink: "https://apps.apple.com/us/app/river-buy-mine-bitcoin/id1536176542", image: "river")
         case .albygo:
-            return .init(index: 13, tag: "albygo", displayName: "Alby Go", link: "alby://",
+            return .init(index: 13, tag: "albygo", displayName: "Alby Go", link: "alby:",
                          appStoreLink: "https://apps.apple.com/us/app/alby-go/id6471335774", image: "alby-go")
             
         }
```

Other than that, the code itself is good for merging. The commits need a bit of tweaking to fully adhere to our contribution guidelines (https://github.com/damus-io/damus/blob/master/docs/CONTRIBUTING.md), but I can easily take care of that for you this time since it's your first PR with us, so don't worry!


**I just need one last thing:** Our guidelines require contributors to signoff their contributions (See https://github.com/damus-io/damus/blob/master/docs/CONTRIBUTING.md#sign-your-work---the-developers-certificate-of-origin)

Usually developers should do that while committing via `git commit --signoff`, but this time you can just send me that via a comment, and I can copy/paste it to the commits. Can you please send me a line like in the example below, with your name and email on it?
```
Signed-off-by: Random J Developer <random@developer.example.org>
```

Thank you!

2025-01-08 13:54 UTC, itstomekk commented
Thank you @danieldaquino !

`Signed-off-by: Tomek K <itstomekk@getalby.com>
`

2025-01-12 03:03 UTC, danieldaquino approved these changes

2025-01-12 03:06 UTC, danieldaquino commented
Performed the final needed tweaks and merged your changes manually! It's now merged on `master` in e106be1412e13282711f73f7eaa06a17df6426a2

Thank you @itstomekk!

2025-01-12 03:06 UTC, closed without merging