Add QR code scanner.
damus-io/damus pull request #733
Opened 2023-03-04 22:24 UTC by suhailsaqan

https://user-images.githubusercontent.com/43693074/222931253-cf0661b2-bd7e-4114-82e3-c75940a7cefb.MP4

2023-03-05 19:57 UTC, jb55 commented
very cool

2023-03-05 19:59 UTC, jb55 commented on damus/Views/QRCodeView.swift
> +            profileView.animation(.easeInOut(duration: 0.3))
is says this is deprecated

2023-03-05 20:04 UTC, jb55 commented on damus/Views/QRCodeView.swift
> +    @State var profileView: NavigationLink<VStack<TupleView<(_ConditionalContent<ProfilePicView, Image>, Text?, Text?)>>, ProfileView>? = nil
this doesn't look right... why is a navigation link in a state variable?

2023-03-05 20:05 UTC, jb55 commented
This is a bit too messy for me to merge atm :(

2023-03-25 22:57 UTC, suhailsaqan commented
@jb55 cleaned it up lol

2023-04-04 17:34 UTC, jb55 commented
taking another look

2023-04-04 17:36 UTC, jb55 commented
code looks a lot better!

2023-04-04 17:39 UTC, jb55 commented
works great, but can we keep the previous design?

2023-04-25 00:26 UTC, jb55 requested changes

2023-04-25 00:26 UTC, jb55 commented on damus/Views/QRCodeView.swift
> +    @State var dst: ProfileView? = nil
views should not be state variables

2023-04-25 00:26 UTC, jb55 commented on damus/Views/QRCodeView.swift
> +                                profile = damus_state.profiles.lookup(id: hex)
The proper way to do this is to make a pubkey state variable instead of the actual view

2023-05-28 15:21 UTC, BenGWeeks commented
Propose that rather than sliding left/right, as it might not be immediately obvious, we have a simple "Scan" button that takes you to the Scan page and a "My Code" on the Scan page that takes you back. This is how WhatsApp works.

FYI @SashaPavlova @robagreda should probably be in the designs too.

2023-05-29 12:36 UTC, BenGWeeks commented
closes [#1149](https://github.com/damus-io/damus/issues/1149)

2023-05-29 19:26 UTC, jb55 commented
On Sun, May 28, 2023 at 08:22:10AM -0700, Ben Weeks wrote:
>Propose that rather than sliding left/right, as it might not be immediately obvious, we have a simple "Scan" button that takes you to the Scan page and a "My Code" on the Scan page that takes you back. This is how WhatsApp works.
>
>FYI @SashaPavlova @robagreda should probably be in the designs too.

Agreed, the sliding thing is weird to me

2023-05-30 15:13 UTC, BenGWeeks commented
Hadn't realized @robagreda had designed this screen up actually. You can find it here:

![CleanShot 2023-05-30 at 16 12 40](https://github.com/damus-io/damus/assets/5950171/e0fded35-a3ee-4996-8ea2-7c6b22897900)

Ref: https://www.figma.com/file/ORaT1T0Ywfbm0sIjwy5Rgq/Damus-iOS?type=design&node-id=0%3A1&t=eCerbHhgYI5tLFQt-1

2023-06-07 06:06 UTC, closed without merging

2023-06-07 06:07 UTC, jb55 commented
Thanks! I merged this in the current state, still needs redesign. @suhailsaqan